apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: parcial-gffh
spec:
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: parcial-gffh
spec:
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: parcial-gffh
spec:
  selector:
    app: app3
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: app4
  namespace: parcial-gffh
spec:
  selector:
    app: app4
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
